// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UohMeetings.Api.Data;

#nullable disable

namespace UohMeetings.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311101759_AttachmentsAndSeed")]
    partial class AttachmentsAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UohMeetings.Api.Entities.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "Order")
                        .IsUnique();

                    b.ToTable("agenda_items", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AgendaMinute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgendaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("agenda_item_id");

                    b.Property<Guid>("MomId")
                        .HasColumnType("uuid")
                        .HasColumnName("mom_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("MomId", "AgendaItemId")
                        .IsUnique();

                    b.ToTable("agenda_minutes", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("StoredFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("stored_file_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "EntityId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbsenceReason")
                        .HasColumnType("text")
                        .HasColumnName("absence_reason");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present");

                    b.Property<Guid>("MomId")
                        .HasColumnType("uuid")
                        .HasColumnName("mom_id");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_object_id");

                    b.HasKey("Id");

                    b.HasIndex("MomId", "UserObjectId")
                        .IsUnique();

                    b.ToTable("mom_attendance", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("user_display_name");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserObjectId")
                        .HasColumnType("text")
                        .HasColumnName("user_object_id");

                    b.Property<string>("UserRoles")
                        .HasColumnType("text")
                        .HasColumnName("user_roles");

                    b.HasKey("Id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("WorkflowTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_template_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("committees", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.CommitteeMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("committee_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_object_id");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId", "UserObjectId")
                        .IsUnique();

                    b.ToTable("committee_members", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MomId")
                        .HasColumnType("uuid")
                        .HasColumnName("mom_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.HasKey("Id");

                    b.HasIndex("MomId");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarEventId")
                        .HasColumnType("text")
                        .HasColumnName("calendar_event_id");

                    b.Property<Guid?>("CommitteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("committee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EndDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime_utc");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("OnlineJoinUrl")
                        .HasColumnType("text")
                        .HasColumnName("online_join_url");

                    b.Property<string>("OnlinePlatform")
                        .HasColumnType("text")
                        .HasColumnName("online_platform");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("StartDateTimeUtc");

                    b.HasIndex("Status");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Mom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<string>("PdfDocUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_doc_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WordDocUrl")
                        .HasColumnType("text")
                        .HasColumnName("word_doc_url");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("moms", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.RecommendationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to_display_name");

                    b.Property<string>("AssignedToEmail")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to_email");

                    b.Property<string>("AssignedToObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_to_object_id");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("committee_id");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date_utc");

                    b.Property<Guid>("MomId")
                        .HasColumnType("uuid")
                        .HasColumnName("mom_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToObjectId");

                    b.HasIndex("MomId");

                    b.HasIndex("Status");

                    b.ToTable("recommendation_tasks", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketOrContainer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket_or_container");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "BucketOrContainer", "ObjectKey")
                        .IsUnique();

                    b.ToTable("stored_files", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SubTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date_utc");

                    b.Property<Guid>("RecommendationTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_task_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationTaskId");

                    b.ToTable("subtasks", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowLuckyDraw")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_lucky_draw");

                    b.Property<Guid?>("CommitteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("committee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<Guid?>("RecommendationTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_task_id");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_audience");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SurveyQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_question_id");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_response_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId", "SurveyQuestionId")
                        .IsUnique();

                    b.ToTable("survey_answers", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text")
                        .HasColumnName("options_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_ar");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_en");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId", "Order")
                        .IsUnique();

                    b.ToTable("survey_questions", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RespondentObjectId")
                        .HasColumnType("text")
                        .HasColumnName("respondent_object_id");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("survey_responses", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteBallot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CastAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cast_at_utc");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_option_id");

                    b.Property<Guid>("VoteSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("vote_session_id");

                    b.Property<string>("VoterDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("voter_display_name");

                    b.Property<string>("VoterObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voter_object_id");

                    b.HasKey("Id");

                    b.HasIndex("VoteSessionId", "VoterObjectId")
                        .IsUnique();

                    b.ToTable("vote_ballots", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("VoteSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("vote_session_id");

                    b.HasKey("Id");

                    b.HasIndex("VoteSessionId", "Order")
                        .IsUnique();

                    b.ToTable("vote_options", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid?>("MomId")
                        .HasColumnType("uuid")
                        .HasColumnName("mom_id");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("vote_sessions", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_state");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "EntityId")
                        .IsUnique();

                    b.ToTable("workflow_instances", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.WorkflowInstanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorObjectId")
                        .HasColumnType("text")
                        .HasColumnName("actor_object_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_state");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("workflow_instance_history", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Name")
                        .IsUnique();

                    b.ToTable("workflow_templates", (string)null);
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AgendaItem", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Meeting", "Meeting")
                        .WithMany("AgendaItems")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AgendaMinute", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Mom", null)
                        .WithMany("AgendaMinutes")
                        .HasForeignKey("MomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Mom", null)
                        .WithMany("Attendance")
                        .HasForeignKey("MomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.CommitteeMember", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Committee", "Committee")
                        .WithMany("Members")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Decision", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Mom", null)
                        .WithMany("Decisions")
                        .HasForeignKey("MomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Meeting", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Committee", "Committee")
                        .WithMany()
                        .HasForeignKey("CommitteeId");

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Mom", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.RecommendationTask", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Mom", null)
                        .WithMany("Recommendations")
                        .HasForeignKey("MomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SubTask", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.RecommendationTask", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("RecommendationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.SurveyResponse", null)
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteBallot", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.VoteSession", null)
                        .WithMany("Ballots")
                        .HasForeignKey("VoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteOption", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.VoteSession", null)
                        .WithMany("Options")
                        .HasForeignKey("VoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.WorkflowInstanceHistory", b =>
                {
                    b.HasOne("UohMeetings.Api.Entities.WorkflowInstance", null)
                        .WithMany("History")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Committee", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Meeting", b =>
                {
                    b.Navigation("AgendaItems");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Mom", b =>
                {
                    b.Navigation("AgendaMinutes");

                    b.Navigation("Attendance");

                    b.Navigation("Decisions");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.RecommendationTask", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.Survey", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.SurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.VoteSession", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("UohMeetings.Api.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
